esphome:
  name: esp8266-barrukoa

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "kAMY+eEvmDOJvr5sqMyMupJ9mPOuOQCq7XHlcSaUOrw="

ota:
  password: "bdbb766a47067f0566e58a12d6dc9624"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
    password: "83mFEzfSnO8S"

captive_portal:

i2c:
  - id: bus_1
    sda: 4
    scl: 5
    scan: True
  

sensor:
  
  - platform: scd4x
    i2c_id: bus_1
    co2:
      name: "CO2"

  - platform: dht
    pin: GPIO16
    temperature:
      name: "Inside Temperature"
    humidity:
      name: "Inside Humidity"
    update_interval: 30s

  - platform: adc
    pin: A0
    name: "Sensor de Humo"
    update_interval: 1s
    filters:
      - multiply: 100
    unit_of_measurement: "%"
    icon: "mdi:percent"
    