esphome:
  name: esp-32-kanpokoa

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Vb+GFDsNzlgmxQ5PniKsVg6mI5GyyjSSHCt1so88IHQ="

ota:
  password: "84781eba113e0752c210b34b1f2571be"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32 Fallback Hotspot"
    password: "hPM4KacDCwuE"

captive_portal:

i2c:
  - id: bus_1
    sda: 4
    scl: 5
    scan: True
  

  - id: bus_2
    sda: GPIO21
    scl: GPIO22
    scan: True
 

sensor:
  - platform: aht10
    i2c_id: bus_1
    temperature:
      name: "Outdoor Temperature"
    humidity:
      name: "Outdoor Humidity"
    update_interval: 10s  



  - platform: bh1750
    i2c_id: bus_2
    name: "Outdoor Illuminance"
    address: 0x23
    update_interval: 10s